### ISSUE TITLE
Serious slowing of database operations

### ISSUE THREAD

**Issue by AlexKovynev** [agileorbit/grails-schwartz#1]
After the migration of jobs in services, execution speed has fallen to 10 times.
It seems that the unused cache. Maybe you have any thoughts?

**Comment by burtbeckwith** [comment]
Would it be possible to share some code demonstrating the problem?

**Comment by AlexKovynev** [comment]
Maybe something like this.
I have a job for periodicaly import data from another source.
Many selects, many updates with comparsions. In quartz all operations take 2 minutes, in schwartz above 20.

``` groovy
Product.list().each {
          if (!ImportTOVAR.findBySch_tovar(it.num.toString()) && !it.deleted) {
                    it.groupment = null
                    it.producer = null
                    it.deleted = true
                    it.save(flush: true)

            }
}
```

**Comment by burtbeckwith** [comment]
When you run this job using the Quartz plugin, you're doing the work entirely in the Job class, right? So there's no active transaction, you're just using the active session that's created for the job?

To get a more realistic comparison, could you try moving the code to a transactional service and calling the service method from the Quartz plugin job? I would expect that to take the same time as the Schwartz plugin running from a service, i.e. the plugins have no effect and the real difference is whether you're running in a transaction or not.

Similarly, create a Schwartz job that's not a transactional service (e.g. use the create-job script with the --pogo flag) and call your code from there. Again the two plugins should take the same time (~2 minutes).

**Comment by AlexKovynev** [comment]
Ok, maybe you are right. But another problem does not give an opportunity to check. Schwartz pojo jobs does not run on grails 3.2.0.RC1:(  I created simple job for test. Maybe my fault?

``` groovy
package sklad

import com.agileorbit.schwartz.StatefulSchwartzJob
import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j
import org.quartz.JobExecutionContext
import org.quartz.JobExecutionException
import org.springframework.stereotype.Component

@Component
@Slf4j
class Testjob implements StatefulSchwartzJob {

    void execute(JobExecutionContext context) throws JobExecutionException {
        println "test"

    }

    void buildTriggers() {
        triggers << factory('repeat').intervalInMillis(500).build()
    }
}
```

**Comment by burtbeckwith** [comment]
Does it show any errors? Or just silently fails?

**Comment by AlexKovynev** [comment]
silently, i just add plugin to dependency, create file (src/main/groovy/sklad/Testjob.groovy) and place code in it. 3.2.1 same result.

**Comment by erichelgeson** [comment]
Closing due to age. If there is still something to look at please open a new issue.
