### ISSUE TITLE
unable to resolve class org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

### ISSUE THREAD

**Issue by ghost** [agileorbit/grails-schwartz#5]
I am trying to "Enable database storage" in Grails schwartz plugin. I am using Postgresql. 

I added: 

```
quartz {
   jdbcStore = true
   properties {
      jobStore {
         driverDelegateClass = PostgreSQLDelegate.name
      }
   }
}
```

as mentioned in the [documentation](http://blog.agileorbit.com/grails-schwartz/latest/index.html#jdbcJobStorage)

However I am getting:

```
script14780880056591519347004.groovy: 1: unable to resolve class org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
 @ line 1, column 1.
   import org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
```

I tried adding additionally: 

` compile 'org.quartz-scheduler:quartz:2.2.3'`

to `build.gradle` without success

. Do I have to include any additional dependency ?

**Comment by erichelgeson** [comment]
Recent versions of Grails require imports to be in `runtime.groovy`. I can add that to the docs. One thing to note is runtime.groovy is  not loaded if applicaiton.groovy does not exist (which I find odd) https://github.com/grails/grails-core/issues/10719 - will update docs to note it.

Also note it was introduced in 3.1.11+ - though not documented yet https://github.com/grails/grails-doc/issues/621
